// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using System.Runtime.InteropServices.ComTypes;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace OperationRoomSystemPC.Model.Patient
{

    public class Result
    {

        [JsonProperty("deptName")]
        public string DeptName { get; set; }

        [JsonProperty("startTime")]
        public string StartTime { get; set; }

        [JsonProperty("birthday")]
        public string Birthday { get; set; }

        [JsonProperty("patientSno")]
        public string PatientSno { get; set; }

        [JsonProperty("patientId")]
        public int PatientId { get; set; }

        [JsonProperty("patientName")]
        public string PatientName { get; set; }

        [JsonProperty("treatType")]
        public int TreatType { get; set; }

        [JsonProperty("patientGender")]
        public int PatientGender { get; set; }

        [JsonProperty("bedNo")]
        public string BedNo { get; set; }

        [JsonProperty("patientNo")]
        public string PatientNo { get; set; }
    }

    public class Model : IRoot
    {

        [JsonProperty("code")]
        public string Code { get; set; }

        [JsonProperty("result")]
        public Result[] Result { get; set; }
    }

}
